#### Importing the libraries

In [49]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

#### Reading the data

In [51]:
data=pd.read_csv('C:/Users/asd/Desktop/Winter Training/data1.csv',header=None)

#### Then we convert the data into numpy arrays

In [52]:
npData=np.asarray(data)
#print(npData)

#### Printing the dimensions, size and shape of the array of data. npData represents the whole data array of 20000X20 dimensions

In [28]:
print('ndim data', npData.ndim)
print('size data', npData.size)
print('shape data', npData.shape)

ndim data 2
size data 400000
shape data (20000, 20)


#### The shape here says that there are 20000 datapoints or inputs we can give to the neural network

20 here suggests that there are 20 different feutures of the data which we are studying and hence signifies the number of input neurons

Doing the same for labels.csv and saving the array of corresponding labels of the data 20000X1 into a numpy array

#### Reading Labels

In [21]:
label=pd.read_csv('C:/Users/asd/Desktop/Winter Training/label1.csv',header=None)
#print(label)

In [29]:
npLabel=np.asarray(label)
print('shape label', npLabel.shape)
print('size label', npLabel.size)
print('ndim label', npLabel.ndim)

shape label (20000, 1)
size label 20000
ndim label 2


In [30]:
print(npLabel)

[[3]
 [2]
 [2]
 ..., 
 [2]
 [2]
 [0]]


#### Converting the labels to oneHot vector format

Then we convert our labels in the one hot format where we convert each labelinto a matrix so that all numbers in the label can be clasified individually

In [44]:
n_values = np.max(npLabel) + 1
oneHotDash=np.eye(n_values)[npLabel]
oneHot=np.reshape(oneHotDash,(20000,5))
print(oneHot.ndim)

2


### Splitting of data and labels

Splitting data into Training data, validation data and testing data inpropotion 80:10:10 using train_test_split function.

We can use data slicing as well - `trainData`= `npData[0:16000]`, `validData`=`npData[16000:18000]`, `testData`=`npData[18000:20000]`

and for labels, `trainLabel`= `npLabel[0:16000]`, `validLabel`=`npLabel[16000:18000]`, `testLabel`=`npLabel[18000:20000]`

In [47]:
from sklearn.model_selection import train_test_split
trainData,testDataDash=train_test_split(npData,train_size=0.8,test_size=0.2,shuffle=False)#divide data in a 80:20 ratio
trainLabel,testLabelDash=train_test_split(oneHot,train_size=0.8,test_size=0.2,shuffle=False)


In [48]:
validateData, testData=train_test_split(testDataDash,train_size=0.5,test_size=0.5,shuffle=False)#dividing rest20% data half half in validation and testing data
validateLabel, testLabel=train_test_split(testLabelDash,train_size=0.5,test_size=0.5,shuffle=False)

There are 20 neurons in the input layer.

There are 5 neurons in the output layer

There are 10 neurons in the hidden layer

Here we take input of the number of neurons in the hidden layer of our single layered neural network


In [55]:
h=input()#number of neurons in the hidden layer
h=int(h)

10


#### Biases are initialized to be zero

In [58]:
b1=np.zeros(h)
b2=np.zeros(5)
print(b1)
print(b2)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.]


#### We make randomized weight matricesaccording to random normal distribution which is according to 0 mean and 1/nL variance or1/sqrt(nL) standard deviation where nL if the number of inuts to that particular laye

In [60]:
std1=(1/np.sqrt(20))#standard deviation of initialiing first weights
std2=(1/np.sqrt(h))#standard deviation of initialiing second weights
w1=np.random.normal(0,std1,(20,h))#gaussian random assignment of weight
w2=np.random.normal(0,std2,(h,5))#gaussian random assignment of weights 
#print("std1\n",std1,"std2\n",std2)
print("w1\n",w1)
print("w2\n",w2)
print(w1.shape)
print(w2.shape)


std1,std2 0.22360679775 0.316227766017
[[ 0.20617593 -0.04174916 -0.19067534 -0.18649261  0.07703732 -0.0990274
   0.27895485  0.02208525  0.03450309  0.40240765]
 [-0.19054476  0.23976541 -0.09972385  0.099872   -0.3299326   0.16675107
  -0.00519006 -0.31873044 -0.14907118  0.09185196]
 [ 0.13424099 -0.31209101  0.13113917  0.20629151 -0.71992843  0.11810456
   0.18763768 -0.17140785  0.20518644  0.06272113]
 [ 0.0655409   0.19310855 -0.19386766  0.28861352 -0.09280006  0.19589783
   0.34356717 -0.25716209 -0.07306113  0.07047695]
 [ 0.03155391  0.0173648  -0.3850587  -0.03490266 -0.02587279 -0.0057679
  -0.25596613  0.07045889  0.5680273   0.22849784]
 [ 0.44250513  0.46558739  0.34171014  0.21249624 -0.2153908  -0.28669305
   0.78319611 -0.05230185 -0.08721683  0.23291369]
 [-0.07531161  0.33987465  0.20570712  0.04369315 -0.14209198 -0.21149821
   0.20410597  0.35005728  0.09773232  0.31115097]
 [-0.10555474  0.3796645   0.36905675  0.33764098 -0.36781468 -0.13480345
   0.10852634 