In [2]:
import numpy as np


In [6]:
a=np.full((4,4),5.1)
print(a)

[[ 5.1  5.1  5.1  5.1]
 [ 5.1  5.1  5.1  5.1]
 [ 5.1  5.1  5.1  5.1]
 [ 5.1  5.1  5.1  5.1]]


In [7]:
a=np.arange(0,7,1)

In [8]:
print(a)

[0 1 2 3 4 5 6]


In [9]:
b =  np.arange(0,20,2)

In [10]:
print(b)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
c  = np.arange(0,300,3)

In [12]:
print(c)

[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51
  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105
 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159
 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213
 216 219 222 225 228 231 234 237 240 243 246 249 252 255 258 261 264 267
 270 273 276 279 282 285 288 291 294 297]


In [13]:
#create an array of even space between the given range of values
a=np.linspace(0, 1, 5)
print(a)

[ 0.    0.25  0.5   0.75  1.  ]


In [14]:
#create an identity matrix of size 3 x 3
a=np.eye(3)
print(a)


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [15]:
#create a 3x4 array with mean of Standard i.e. N(0,1)
a=np.random.normal(0, 1, (3,4))
print(a)

[[-0.33081073 -0.24333905 -0.79608776 -0.29234811]
 [-0.67762414 -0.01162852 -1.06047824  0.46709763]
 [ 1.25761538  0.96610614  1.23839137  2.07633375]]


In [17]:
#create a 3x4x5 array with mean 0 and standard deviation 2 in a norm
#al Distribution i.e. N(1.4,4)
a=np.random.normal(1.4, 2, (3,4,5))
print(a)


[[[ 3.18001669  3.0416034  -2.29658078  3.54356589  2.10381856]
  [ 1.4399458   3.35645096  3.74357423  1.96616551  2.34517845]
  [ 0.72282938  3.0774711   2.385286   -0.41076023 -1.35792778]
  [ 1.69986411  1.5353013  -0.46133633  3.25387849 -2.41678185]]

 [[ 6.09539816  2.00644161  0.14354534 -0.49542026  1.27949795]
  [ 0.88761482  4.16424686 -0.30252056 -0.53949141  0.60028558]
  [ 0.04612524  0.37511698  4.15437506  0.55161763  0.62802035]
  [-0.57573435 -0.31367908 -0.08335371 -0.16873229  5.69603773]]

 [[ 2.22557614  1.32963622  1.21981311  1.82040101  3.98050014]
  [ 3.96743158  2.19703934  5.79177947  1.63341201  3.13550079]
  [ 1.94839429  3.95692135  5.21627908  0.13155356  1.44424076]
  [ 3.55942541  4.59313214  1.25508932  0.97588913  2.13277794]]]


In [19]:
#to understand below function
a = np.random.randint(10, size=10) #one dimension
print(a)


[1 0 9 1 9 3 4 5 4 0]


In [20]:
a = np.random.randint(10, size=(3,4)) #two dimension
print(a)


[[9 6 1 5]
 [3 5 8 3]
 [8 5 6 3]]


In [21]:
#set a random seed
np.random.seed(0)
x1 = np.random.randint(10, size=6) #one dimension
x2 = np.random.randint(10, size=(3,4)) #two dimension
x3 = np.random.randint(10, size=(3,4,5)) #three dimension
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
# x3 ndim: 3
# x3 shape: (3, 4, 5)
# x3 size: 60

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


In [22]:
#The important thing to remember is that indexing in python starts at zero.

In [24]:
a = np.array([7, 3, 4, 5, 8, 2])

print(a)
#[4 3 4 4 8 4]
print(a[0])
#7
print(a[2])
#4
print(a[-1])
#2
print(a[-2])
#8
#In a multidimensional array, we need to specify row and column inde

a=np.array([[3, 7, 5, 5],[0, 1, 5, 9],[3, 0, 5, 0]])
print(a)
# [[3 7 5 5]
# [0 1 5 9]
# [3 0 5 0]]
#1st row and 2nd column value
print(a[0,1])
#7
#3rd row and last value from the 3rd column
print(a[2,-1])
#0
#Replace value at 0,0 index
a[0,0] = 12
print(a)
# [[12 7 5 5]
# [0 1 5 9]
# [3 0 5 0]]

[7 3 4 5 8 2]
7
4
2
8
[[3 7 5 5]
 [0 1 5 9]
 [3 0 5 0]]
7
0
[[12  7  5  5]
 [ 0  1  5  9]
 [ 3  0  5  0]]


In [25]:
x = np.arange(10)

print(x)
#[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
#from start to 4th position
print(x[:5])
#[0, 1, 2, 3, 4]
#from 4th position to end
print(x[4:])
#[4, 5, 6, 7, 8, 9]
#from 4th to 6th position
print(x[4:7])
#[4, 5, 6]

#Return elements at even place
print(x[ : : 2])
#[0, 2, 4, 6, 8]
#Return elements from first position step by two
print(x[1::2])
#[1, 3, 5, 7, 9]
#Reverse the array
print(x[::-1])
#[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[4 5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [27]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print('First array:' )
print (a)
print()
print ('Second array:' )
print (b)
print()
print ('First Array + Second Array' )
print (a + b)

First array:
[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]]

Second array:
[ 1.  2.  3.]

First Array + Second Array
[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]


In [28]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))
# [[ 6.0 8.0]
# [10.0 12.0]]
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))
# [[-4.0 -4.0]
# [-4.0 -4.0]]
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))
# [[ 5.0 12.0]
# [21.0 32.0]]
# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))
# [[ 0.2 0.33333333]
# [ 0.42857143 0.5 ]]
# Elementwise square root; produces the array
print(np.sqrt(x))
# [[ 1. 1.41421356]
# [ 1.73205081 2. ]]
# Elementwise square root; produces the array
print(np.exp(x))
# [[ 2.71828183 7.3890561 ]
# [ 20.08553692 54.59815003]]

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]
[[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]]


In [29]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
# [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [32]:
x = np.random.randint(7,size=(3,4))

print(x)
# [[4 0 5 0]
# [3 2 3 2]
# [4 6 3 6]]
print(np.sum(x)) # Compute sum of all elements; prints "38"
print(np.sum(x, axis=0)) # Compute sum of each column; prints "[11 8 11 8]"
print(np.sum(x, axis=1)) # Compute sum of each row; prints "[9 10 19]"

[[4 3 4 4]
 [4 0 6 4]
 [3 2 5 5]]
44
[11  5 15 13]
[15 14 15]


In [33]:
x  = np.random.randn(3,5)
print(x)
# [[ 1.25441407 1.41910204 -0.74385608 -2.5174371 -1.50709602]
# [ 1.14907613 -1.19357825 1.14104245 1.50944508 1.06777513]
# [-0.68658948 0.01487332 -0.3756659 -0.03822364 0.36797447]]
print(x.T)
# [[ 1.25441407 1.14907613 -0.68658948]
# [ 1.41910204 -1.19357825 0.01487332]
# [-0.74385608 1.14104245 -0.3756659 ]
# [-2.5174371 1.50944508 -0.03822364]
# [-1.50709602 1.06777513 0.36797447]]
# Note that taking the transpose of a rank 1 array does nothing:
v = np.random.randint(3,12,size=5)
print(v)
# [11 9 9 4 9]
print(v.T) # Prints "[1 2 3]"
# [11 9 9 4 9]

[[-0.89546656  0.3869025  -0.51080514 -1.18063218 -0.02818223]
 [ 0.42833187  0.06651722  0.3024719  -0.63432209 -0.36274117]
 [-0.67246045 -0.35955316 -0.81314628 -1.7262826   0.17742614]]
[[-0.89546656  0.42833187 -0.67246045]
 [ 0.3869025   0.06651722 -0.35955316]
 [-0.51080514  0.3024719  -0.81314628]
 [-1.18063218 -0.63432209 -1.7262826 ]
 [-0.02818223 -0.36274117  0.17742614]]
[6 7 4 5 4]
[6 7 4 5 4]


In [34]:
x = np.random.randn(3,5)
print(x)
# [[ 1.25441407 1.41910204 -0.74385608 -2.5174371 -1.50709602]
# [ 1.14907613 -1.19357825 1.14104245 1.50944508 1.06777513]
# [-0.68658948 0.01487332 -0.3756659 -0.03822364 0.36797447]]
print(x.T)
# [[ 1.25441407 1.14907613 -0.68658948]
# [ 1.41910204 -1.19357825 0.01487332]
# [-0.74385608 1.14104245 -0.3756659 ]
# [-2.5174371 1.50944508 -0.03822364]
# [-1.50709602 1.06777513 0.36797447]]
# Note that taking the transpose of a rank 1 array does nothing:
v = np.random.randint(3,12,size=5)
print(v)
# [11 9 9 4 9]
print(v.T) # Prints "[1 2 3]"
# [11 9 9 4 9]

[[-0.40178094 -0.22403878 -0.42018339  0.99982969  0.43103415]
 [-0.65091287 -1.49874039 -1.23063497  0.19400719 -0.99838235]
 [-0.3676376   1.73719932  0.59361275 -0.54236358 -1.71967238]]
[[-0.40178094 -0.65091287 -0.3676376 ]
 [-0.22403878 -1.49874039  1.73719932]
 [-0.42018339 -1.23063497  0.59361275]
 [ 0.99982969  0.19400719 -0.54236358]
 [ 0.43103415 -0.99838235 -1.71967238]]
[11  6 11  5 11]
[11  6 11  5 11]


In [ ]:
# In the above examples, wherever I used random array as an input. This output is generated by me. You
# may find different values when you try to run it. However, the operation remains same